version: 0.0
os: linux
files:
  - source: ./
    destination: /tmp/nginx/
    file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/stop_nginx.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/start_nginx.sh
      timeout: 300
      runas: root